import { NavGroupType, NavItem } from "./types";
import { RouteName } from "./routeNames";

export const NAV_ROUTES: NavItem[] = [
  {
    id: "dashboard",
    type: NavGroupType.MAIN,
    title: "Dashboard",
    href: RouteName.DASHBOARD,
    icon: "mdi:view-dashboard-outline",
    visible: true,
  },
  {
    id: "observability",
    type: NavGroupType.SYSTEM,
    title: "Observability Overview",
    href: RouteName.OBSERVABILITY,
    icon: "mdi:eye-outline",
    visible: true,
  },
  {
    id: "logs",
    type: NavGroupType.SYSTEM,
    title: "Live Log Monitor",
    href: RouteName.LOGS,
    icon: "mdi:monitor-eye",
    visible: true,
  },
  {
    id: "summary",
    type: NavGroupType.SERVICES,
    title: "Summary",
    href: RouteName.SERVICES_SUMMARY,
    icon: "mdi:text-box-outline",
    visible: true,
  },
  {
    id: "proxy-list",
    type: NavGroupType.SERVICES,
    title: "Proxy List",
    href: RouteName.SERVICES_PROXIES,
    icon: "mdi:server",
    visible: true,
  },
  {
    id: "settings",
    type: NavGroupType.SERVICES,
    title: "User Settings",
    href: RouteName.SETTINGS,
    icon: "mdi:cog-outline",
    visible: true,
  },
  {
    id: "products",
    type: NavGroupType.SERVICES,
    title: "All Products",
    href: RouteName.PRODUCTS,
    icon: "mdi:shopping-outline",
    visible: true,
  },
  {
    id: "api-keys",
    type: NavGroupType.DEVELOPER,
    title: "API Keys",
    href: RouteName.API_KEYS,
    icon: "mdi:key-outline",
    visible: true,
  },
  {
    id: "api-requests",
    type: NavGroupType.DEVELOPER,
    title: "API Requests",
    href: RouteName.API_REQUESTS,
    icon: "mdi:api",
    visible: true,
  },
  {
    id: "resellers",
    type: NavGroupType.AFFILIATE,
    title: "Resellers Statistics",
    href: RouteName.RESELLERS,
    icon: "mdi:chart-bar",
    visible: true,
  },
  {
    id: "affiliate",
    type: NavGroupType.AFFILIATE,
    title: "Affiliate Program",
    href: RouteName.AFFILIATE,
    icon: "mdi:account-multiple-outline",
    visible: true,
  },
  {
    id: "billing",
    type: NavGroupType.SUPPORT,
    title: "Billing",
    href: RouteName.BILLING,
    icon: "mdi:credit-card-outline",
    visible: true,
    endIcon: "mdi:menu-right",
  },
  {
    id: "help",
    type: NavGroupType.SUPPORT,
    title: "Help",
    href: RouteName.HELP,
    icon: "mdi:help-circle-outline",
    visible: true,
    endIcon: "mdi:menu-right",
  },
];
